name: project_structure
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^8.0.0
  # Bloc for state management
  flutter_bloc: ^8.1.6
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  connectivity: ^3.0.6
  http: ^1.2.2
  # Local cache
  shared_preferences: ^2.3.2
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
